services:

  postgres:
   image: bitnami/postgresql
   container_name: passin-db
   ports:
     - 5432:5432
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=passin
   volumes:
     - 'db:/bitnami/postgresql'
   networks:
     - passin

  passin-api:
   build:
    context: .
    dockerfile: Dockerfile
   image: gpmarchi/passin-api
   container_name: passin-api
   ports:
    - "3333:3333"
   environment:
     - DATABASE_URL=postgresql://admin:admin@postgres:5432/passin
     - API_BASE_URL=http://localhost:3333
     - PORT=3333
   depends_on:
     - postgres
   networks:
     - passin

networks:
  passin:
   driver: bridge

volumes:
  db: